// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// <auto-generated>This file has been auto generated from 'src\OpenTelemetry.SemanticConventions\scripts\templates\registry\SemanticConventionsAttributes.cs.j2' </auto-generated>

#nullable enable

#pragma warning disable CS1570 // XML comment has badly formed XML

namespace ModernObservability.Conventions;

/// <summary>
/// Constants for semantic attribute names outlined by the OpenTelemetry specifications.
/// </summary>
public static class PersonAttributes
{
    /// <summary>
    /// The age of the person.
    /// </summary>
    public const string AttributePersonAge = "person.age";

    /// <summary>
    /// The email address of the person.
    /// </summary>
    public const string AttributePersonEmail = "person.email";

    /// <summary>
    /// The first name of the person.
    /// </summary>
    public const string AttributePersonFirstname = "person.firstname";

    /// <summary>
    /// The surname of the person.
    /// </summary>
    public const string AttributePersonSurname = "person.surname";
}